### ISSUE TITLE
Create Ceres pip package

### ISSUE THREAD

**Issue by acs** [dicortazar/ceres#9]
In order to use Ceres in GrimoireLab, a pip package must exists in order to install it.

**Comment by dicortazar** [comment]
Thanks for the bug report. There is a first installable version merged at #10 thanks to @jgbarah (thanks!).

**Comment by jgbarah** [comment]
New pr #11 with better dependencies.

When trying to upload the package to pypi, it seems the name is taken (even when there is no published release). Did any of you take it? (I see no way of figuring out who has the name).

**Comment by jgbarah** [comment]
I found out about the owner of the name:

https://pypi.org/project/ceres/

I've contacted him to see if there is any chance that he transfers the package name.

**Comment by dicortazar** [comment]
The new name is cereslib and was finally uploaded to Pypi. I guess we can close this ticket :).
